/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_whvixd_demo_jdk_jni_HelloNative */

#ifndef _Included_HelloNative
#define _Included_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_whvixd_demo_jdk_jni_HelloNative
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloNative_hello(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
